Repository nasa/cumulus-dashboard, pull requests merged in 2020-11, with the labels that each got.

#871 Cumulus 2225 Add "Error Type" filter and sorting
  CHANGELOG.md
  app/src/js/components/DropDown/dropdown.js
  app/src/js/components/Granules/list.js
  app/src/js/components/locale.js
  app/src/js/utils/table-config/granules.js
  cypress/fixtures/seeds/granulesFixture.json
  cypress/integration/granules_spec.js
  cypress/integration/main_page_spec.js
Labels: PR Feedback

#873 Bugfix: Update error name in tests.
  cypress/integration/main_page_spec.js
Labels: Needs Review

#875 Mhs/cumulus 2242/cleanup docker builds
  .circleci/config.yml
  CHANGELOG.md
  README.md
  app/src/js/config/index.js
  bin/build_dashboard_image.sh
  bin/build_dashboard_via_docker.sh
  bin/build_in_docker.sh
  cypress/integration/granules_spec.js
  docker/nginx.conf
  localAPI/docker-compose-cypress.yml
  package-lock.json
  package.json
Labels: Needs Review

#874 CUMULUS-2147:Clear execution errors from granules list
  CHANGELOG.md
  app/src/js/actions/index.js
  app/src/js/actions/types.js
  app/src/js/components/BatchAsyncCommands/BatchAsyncCommands.js
  app/src/js/components/ListActions/ListActions.js
  app/src/js/reducers/granules.js
  app/src/js/utils/table-config/granules.js
Labels: In Review

#882 Mhs/cumulus 2242/tweaks for running and building dashboard
  .circleci/config.yml
  package.json
Labels: Needs Review

#888 Mhs/cumulus 2242/ Generally documentation changes found prepping for bootcamp
  .eslintignore
  README.md
  localAPI/README.md
Labels: In Review

#880 CUMULUS 2206 Performance updates
  .eslintrc
  CHANGELOG.md
  app/src/css/_base.scss
  app/src/js/App.js
  app/src/js/components/Collections/granules.js
  app/src/js/components/Collections/list.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/DatePickerHeader/DatePickerHeader.js
  app/src/js/components/Executions/execution-events.js
  app/src/js/components/Executions/execution-status-graph.js
  app/src/js/components/Executions/overview.js
  app/src/js/components/Form/_form.scss
  app/src/js/components/Granules/index.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/Operations/overview.js
  app/src/js/components/Pagination/pagination.js
  app/src/js/components/Pdr/index.js
  app/src/js/components/Pdr/list.js
  app/src/js/components/Pdr/overview.js
  app/src/js/components/Providers/overview.js
  app/src/js/components/ReconciliationReports/create.js
  app/src/js/components/ReconciliationReports/list.js
  app/src/js/components/Rules/overview.js
  app/src/js/components/SortableTable/SortableTable.js
  app/src/js/components/Table/Table.js
  app/src/js/components/home.js
  app/src/js/utils/table-config/execution-status.js
  package-lock.json
  package.json
  test/components/table/list-view.js
Labels: PR Feedback

#886 [CUMULUS-2169] Collection Overview - display Provider as search input
  CHANGELOG.md
  app/src/js/actions/index.js
  app/src/js/actions/types.js
  app/src/js/components/Collections/granules.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/locale.js
  app/src/js/reducers/providers.js
  cypress/integration/collections_spec.js
  cypress/integration/granules_spec.js
  test/components/granules/overview.js
  test/reducers/providers.js
Labels: In Review
