Repository nasa/cumulus-dashboard, pull requests merged in 2020-06, with the labels that each got.

#782 [CUMULUS-1918]Add delete button to Reconciliation Reports
  CHANGELOG.md
  app/src/css/_buttons.scss
  app/src/js/actions/index.js
  app/src/js/components/ReconciliationReports/list.js
  app/src/js/utils/table-config/reconciliation-reports.js
  cypress/fixtures/seeds/reconciliationReportFixture.json
  cypress/integration/reconciliation_spec.js
Labels: In Review

#784 CUMULUS-1842: Fix dashboard sort issue
  CHANGELOG.md
  app/src/js/components/SortableTable/SortableTable.js
  app/src/js/components/Workflows/overview.js
  app/src/js/utils/table-config/executions.js
  app/src/js/utils/table-config/granules.js
  app/src/js/utils/table-config/rules.js
  app/src/js/utils/table-config/workflows.js
  babel.config.js
  cypress/integration/collections_spec.js
  cypress/integration/granules_spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: Needs Review

#785 show valid reports
  CHANGELOG.md
  app/src/css/_badges.scss
  app/src/css/_base.scss
  app/src/css/_buttons.scss
  app/src/css/utils/variables/_colors.scss
  app/src/css/vendor/bootstrap/_bootstrap.scss
  app/src/css/vendor/bootstrap/overrides/_card.scss
  app/src/css/vendor/bootstrap/overrides/_multicard.scss
  app/src/js/components/Collections/granules.js
  app/src/js/components/Collections/list.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/Executions/execution-events.js
  app/src/js/components/Executions/overview.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/Logs/viewer.js
  app/src/js/components/Operations/overview.js
  app/src/js/components/Pdr/list.js
  app/src/js/components/Pdr/overview.js
  app/src/js/components/Pdr/pdr.js
  app/src/js/components/Providers/overview.js
  app/src/js/components/ReconciliationReports/reconciliation-report.js
  app/src/js/components/ReconciliationReports/reshape-report.js
  app/src/js/components/ReconciliationReports/table-cards.js
  app/src/js/components/Rules/overview.js
  app/src/js/components/Rules/rule.js
  app/src/js/components/Table/TableFilters.js
  app/src/js/components/Workflows/overview.js
  app/src/js/components/home.js
  cypress/fixtures/seeds/reconciliation-reports/inventoryReport-20200114T202529026.json
  cypress/integration/executions_spec.js
  cypress/integration/reconciliation_spec.js
  package.json
  test/components/reconciliation-reports/reconciliation-report.js
Labels: PR Feedback

#789 CUMULUS-2019: Support partial search
  CHANGELOG.md
  USAGE.md
  app/src/js/actions/index.js
  app/src/js/components/Executions/overview.js
  app/src/js/components/Operations/overview.js
  app/src/js/components/Table/Table.js
  app/src/js/reducers/collections.js
  app/src/js/reducers/executions.js
  app/src/js/reducers/granules.js
  app/src/js/reducers/operations.js
  app/src/js/reducers/pdrs.js
  app/src/js/reducers/providers.js
  app/src/js/reducers/reconciliation-reports.js
  app/src/js/reducers/rules.js
  cypress/integration/granules_spec.js
  package-lock.json
  package.json
Labels: In Review

#788 CUMULUS-1872 Granules timers
  CHANGELOG.md
  app/src/css/_badges.scss
  app/src/js/components/Collections/granules.js
  app/src/js/components/Granules/bulk-granule-modal.js
  app/src/js/components/Granules/bulk.js
  app/src/js/components/Granules/granule.js
  app/src/js/components/Granules/index.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/Pdr/index.js
  app/src/js/components/Pdr/list.js
  test/components/granules/granule.js
  test/components/granules/overview.js
Labels: PR Feedback

#793 [CUMULUS-1882] Fix TEA Lambda metrics
  CHANGELOG.md
  app/src/js/actions/action-config/teaLambdaSearch.js
  app/src/js/utils/kibana.js
  test/utils/kibana.js
Labels: In Review
