Repository nasa/cumulus-dashboard, pull requests merged in 2020-05, with the labels that each got.

#746 CUMULUS-1777: Update dashboard to log out user on 401/403 response from API
  app/src/js/components/Header/header.js
  app/src/js/middleware/request.js
  test/actions/login.js
  test/middleware/request.js
Labels: In Review

#757 Prevents accidental overwrite of this.cancelInterval
  app/src/js/components/home.js
Labels: Needs Review

#754 [CUMULUS-1903] Tabs for reconciliation report buckets
  CHANGELOG.md
  TABLES.md
  app/src/css/_base.scss
  app/src/css/vendor/bootstrap/_bootstrap.scss
  app/src/css/vendor/bootstrap/overrides/_card.scss
  app/src/js/components/Collections/granules.js
  app/src/js/components/Collections/list.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/Executions/execution-events.js
  app/src/js/components/Executions/overview.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/Operations/overview.js
  app/src/js/components/Pagination/pagination.js
  app/src/js/components/Pagination/simple-pagniation.js
  app/src/js/components/Pdr/overview.js
  app/src/js/components/Providers/overview.js
  app/src/js/components/ReconciliationReports/index.js
  app/src/js/components/ReconciliationReports/list.js
  app/src/js/components/ReconciliationReports/reconciliation-report.js
  app/src/js/components/ReconciliationReports/report-table.js
  app/src/js/components/ReconciliationReports/table-cards.js
  app/src/js/components/Rules/overview.js
  app/src/js/components/SortableTable/SortableTable.js
  app/src/js/components/Table/Table.js
  app/src/js/components/Workflows/overview.js
  app/src/js/components/home.js
  cypress/integration/reconciliation_spec.js
  test/components/reconciliation-reports/reconciliation-report.js
  test/components/reconciliation-reports/report-table.js
  test/components/table/list-view.js
Labels: PR Feedback

#761 Workaround to resolve intermittent failure in collection_spec
  app/src/js/components/Form/_form.scss
  cypress/integration/collections_spec.js
Labels: In Review

#769 [CUMULUS-1916] Update reconciliation report columns
  CHANGELOG.md
  app/src/js/components/ReconciliationReports/list.js
  app/src/js/components/SortableTable/SortableTable.js
  app/src/js/components/Table/Table.js
  app/src/js/reducers/reconciliation-reports.js
  app/src/js/utils/format.js
  app/src/js/utils/table-config/reconciliation-reports.js
  cypress/integration/reconciliation_spec.js
  test/reducers/reconciliation-reports.js
Labels: Needs Review

#771 Mhs/cumulus 1916/seed reconcilation reports
  CHANGELOG.md
  cypress/fixtures/seeds/reconciliation-reports/inventoryReport-20200114T202529026.json
  cypress/fixtures/seeds/reconciliation-reports/inventoryReport-20200114T205238781.json
  cypress/fixtures/seeds/reconciliationReportFixture.json
  cypress/integration/auth_spec.js
  cypress/integration/reconciliation_spec.js
  cypress/plugins/seedEverything.js
  package-lock.json
  package.json
Labels: PR Feedback
