Repository nasa/cumulus-dashboard, pull requests merged in 2020-12, with the labels that each got.

#900 [CUMULUS 2071] Update card interactions
  CHANGELOG.md
  app/src/css/modules/_table.scss
  app/src/css/vendor/bootstrap/overrides/_card.scss
  app/src/js/components/home.js
Labels: PR Feedback

#905 Repository side of changes for CUMULUS-2280
  CHANGELOG.md
  bamboo/detect-pr.js
  bamboo/set-bamboo-env-variables.sh
  bamboo/set-status.sh
  localAPI/docker-compose-cypress.yml
  localAPI/docker-compose-dashboard.yml
  localAPI/docker-compose-serve-api.yml
  localAPI/docker-compose.yml
  package.json
Labels: In Review

#907 Replace CircleCI with Earthdata Bamboo
  .circleci/config.yml
  CHANGELOG.md
  DEVELOPMENT.md
  README.md
Labels: Needs Review

#902 [CUMULUS-2269] Remove request-promise
  CHANGELOG.md
  app/src/js/actions/helpers.js
  app/src/js/actions/index.js
  app/src/js/components/Add/add.js
  app/src/js/components/Errors/report.js
  app/src/js/components/Executions/execution-status.js
  app/src/js/components/Form/Form.js
  app/src/js/components/Granules/bulk-granule-modal.js
  app/src/js/components/Header/header.js
  app/src/js/components/LoginModal/login-modal.js
  app/src/js/components/TextAreaForm/text-area.js
  app/src/js/components/TopButton/TopButton.js
  app/src/js/components/oauth.js
  app/src/js/middleware/request.js
  app/src/js/reducers/logs.js
  app/src/js/reducers/stats.js
  app/src/js/store/configureStore.js
  app/src/js/utils/auth.js
  app/src/js/utils/browser.js
  app/src/js/utils/download-file.js
  app/src/js/utils/table-config/granules.js
  app/src/js/utils/table-config/reconciliation-reports.js
  app/src/js/utils/typeahead-helpers.js
  app/src/js/utils/url-helper.js
  cypress/fixtures/rule-error.json
  cypress/integration/rules_spec.js
  cypress/validation-tests/main-page.js
  package-lock.json
  package.json
  test/_setup-browser-env.js
  test/actions/datefilters.js
  test/actions/helpers.js
  test/actions/recover.js
  test/actions/store.js
  test/components/executions/execution-status.js
  test/components/form/edit-record.js
  test/components/granules/overview.js
  test/components/table/list-view.js
  test/middleware/request.js
  test/reducers/stats.js
  webpack.common.js
Labels: In Review

#913 [CUMULUS-2322] Pagination bugfix
  CHANGELOG.md
  app/src/js/components/SortableTable/SortableTable.js
  cypress/integration/main_page_spec.js
  cypress/integration/reconciliation_spec.js
  package-lock.json
  package.json
Labels: Needs Review
