Repository nasa/cumulus-dashboard, pull requests merged in 2020-04, with the labels that each got.

#711 styling for rules overview page
  CHANGELOG.md
  app/src/css/_base.scss
  app/src/css/_buttons.scss
  app/src/js/components/Button/Button.scss
  app/src/js/components/Rules/index.js
  app/src/js/components/Rules/overview.js
  app/src/js/utils/table-config/rules.js
  cypress/integration/rules_spec.js
Labels: Needs Review

#713 Cumulus 1515 workflow search filter
  CHANGELOG.md
  README.md
  app/src/js/actions/index.js
  app/src/js/actions/types.js
  app/src/js/components/Workflows/overview.js
  app/src/js/config/config.js
  app/src/js/reducers/workflows.js
  app/src/js/utils/table-config/workflows.js
  cypress/integration/workflows_spec.js
  package-lock.json
  package.json
  test/reducers/workflows.js
  test/utils/table-config/workflows.js
  webpack.common.js
Labels: Needs Review

#712 CUMULUS-1528
  CHANGELOG.md
  app/src/css/_buttons.scss
  app/src/js/actions/index.js
  app/src/js/components/Add/add.js
  app/src/js/components/Datepicker/Datepicker.js
  app/src/js/components/Form/Form.js
  app/src/js/components/Form/_form.scss
  app/src/js/components/FormSchema/schema.js
  app/src/js/components/Rules/add.js
  app/src/js/utils/validate.js
  cypress/integration/providers_spec.js
  cypress/integration/rules_spec.js
  package.json
  test/components/form/edit-record.js
Labels: In Review

#700 [CUMULUS-1787] Update listCollections to use /active when time is selected
  CHANGELOG.md
  app/src/js/actions/index.js
  cypress/integration/collections_spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: In Review, Needs Review

#706 [CUMULUS-1646] Update dashboard pagination to include option for choosing number of records
  CHANGELOG.md
  app/src/js/actions/index.js
  app/src/js/actions/types.js
  app/src/js/components/Collections/granules.js
  app/src/js/components/Collections/list.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/Executions/overview.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/Operations/overview.js
  app/src/js/components/Pdr/list.js
  app/src/js/components/Pdr/overview.js
  app/src/js/components/Providers/overview.js
  app/src/js/components/ReconciliationReports/list.js
  app/src/js/components/Rules/overview.js
  app/src/js/config/index.js
  app/src/js/reducers/rules.js
  app/src/js/utils/page-size.js
  cypress/fixtures/seeds/granulesFixture.json
  cypress/integration/collections_spec.js
  cypress/integration/granules_spec.js
  cypress/integration/main_page_spec.js
Labels: Needs Review

#728 Note on where do find information on how to serve the dashboard.
  README.md
Labels: Needs Review

#727 Cumulus 1460 Update Dashboard Header
  CHANGELOG.md
  app/src/js/components/Providers/index.js
  app/src/js/components/Providers/overview.js
  app/src/js/components/ReconciliationReports/index.js
  app/src/js/components/ReconciliationReports/list.js
  cypress/integration/providers_spec.js
Labels: In Review

#722 [CUMULUS-1813] Fix execution graph on Execution page
  CHANGELOG.md
  app/src/css/_chart.scss
  app/src/css/_normalize.scss
  app/src/css/main.scss
  app/src/js/components/Executions/execution-status-graph.js
  app/src/js/components/Executions/index.js
  cypress/integration/executions_spec.js
  package-lock.json
Labels: PR Feedback

#734 Cumulus 1677 modal workflow updates
  CHANGELOG.md
  app/src/js/components/BatchAsyncCommands/BatchAsyncCommands.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/Executions/execution-status-graph.js
  app/src/js/components/ReingestGranules/BatchReingestCompleteContent.js
  app/src/js/components/ReingestGranules/BatchReingestConfirmContent.js
  app/src/js/utils/table-config/granules.js
  cypress/integration/collections_spec.js
  cypress/integration/granules_spec.js
  cypress/integration/main_page_spec.js
  package-lock.json
  package.json
  test/components/ReingestGranules/BatchReingestCompleteContent.js
  test/components/ReingestGranules/BatchReingestConfirmContent.js
  test/utils/table-config/granules.js
Labels: Needs Review

#736 [CUMULUS-1685] Edit rule tests
  app/src/js/components/EditRaw/edit-raw.js
  app/src/js/components/Modal/modal.js
  app/src/js/components/Providers/provider.js
  cypress/integration/collections_spec.js
  cypress/integration/rules_spec.js
Labels: PR Feedback
