Repository nasa/cumulus-dashboard, pull requests merged in 2020-03, with the labels that each got.

#661 Remove histogram
  CHANGELOG.md
  app/src/css/main.scss
  app/src/js/actions/index.js
  app/src/js/actions/types.js
  app/src/js/components/Chart/_chart.scss
  app/src/js/components/Chart/histogram.js
  app/src/js/reducers/stats.js
  test/components/granules/overview.js
Labels: Needs Review

#662 [CUMULUS-1758] Use react-table for resizing columns
  CHANGELOG.md
  TABLES.md
  app/src/css/modules/_table.scss
  app/src/js/components/Collections/granules.js
  app/src/js/components/Collections/list.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/Executions/execution-status.js
  app/src/js/components/Executions/overview.js
  app/src/js/components/Granules/granule.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/Operations/overview.js
  app/src/js/components/Pdr/list.js
  app/src/js/components/Pdr/overview.js
  app/src/js/components/Pdr/pdr.js
  app/src/js/components/Providers/overview.js
  app/src/js/components/ReconciliationReports/list.js
  app/src/js/components/ReconciliationReports/reconciliation-report.js
  app/src/js/components/ReconciliationReports/report-table.js
  app/src/js/components/Rules/overview.js
  app/src/js/components/SortableTable/SortableTable.js
  app/src/js/components/Table/Table.js
  app/src/js/components/Workflows/overview.js
  app/src/js/components/home.js
  app/src/js/utils/table-config/collections.js
  app/src/js/utils/table-config/execution-status.js
  app/src/js/utils/table-config/executions.js
  app/src/js/utils/table-config/granules.js
  app/src/js/utils/table-config/instances.js
  app/src/js/utils/table-config/operations.js
  app/src/js/utils/table-config/pdr-progress.js
  app/src/js/utils/table-config/pdrs.js
  app/src/js/utils/table-config/providers.js
  app/src/js/utils/table-config/queues.js
  app/src/js/utils/table-config/reconciliation-reports.js
  app/src/js/utils/table-config/rules.js
  app/src/js/utils/table-config/services.js
  app/src/js/utils/table-config/workflows.js
  cypress/integration/collections_spec.js
  cypress/integration/executions_spec.js
  cypress/integration/granules_spec.js
  cypress/integration/providers_spec.js
  cypress/integration/reconciliation_spec.js
  cypress/integration/rules_spec.js
  cypress/integration/workflows_spec.js
  package-lock.json
  package.json
  test/components/executions/execution-status.js
  test/components/granules/granule.js
  test/components/reconciliation-reports/report-table.js
  test/components/table/list-view.js
  test/utils/pdrs.js
Labels: Needs Review

#663 Cumulus 1504
  app/src/css/_base.scss
  app/src/css/_buttons.scss
  app/src/css/modules/_table.scss
  app/src/js/components/Button/Button.scss
  app/src/js/components/Collections/index.js
  app/src/js/components/Collections/list.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/DeleteCollection/DeleteCollection.js
  app/src/js/components/Form/_form.scss
  app/src/js/components/ListActions/ListActions.js
  app/src/js/components/Overview/overview.js
  app/src/js/components/locale.js
  app/src/js/utils/table-config/collections.js
  cypress/integration/collections_spec.js
  cypress/integration/executions_spec.js
  cypress/integration/granules_spec.js
Labels: Needs Review

#676 Suggest: add back tests for values in granule overview
  cypress/integration/executions_spec.js
  cypress/integration/granules_spec.js
Labels: Needs Review

#679 webpack environment: fix the default value lookup for HIDE_PDR
  webpack.common.js
Labels: Needs Review

#690 [CUMULUS-1535] Add confirmation modal for editing a rule
  CHANGELOG.md
  app/src/js/components/Collections/edit.js
  app/src/js/components/EditRaw/edit-raw.js
  app/src/js/components/Rules/edit.js
  cypress/integration/collections_spec.js
  cypress/integration/rules_spec.js
Labels: PR Feedback

#694 Cumulus 1798 mhs
  CHANGELOG.md
  app/src/js/components/Datepicker/Datepicker.js
  app/src/js/components/Datepicker/Datepicker.scss
  app/src/js/reducers/datepicker.js
  app/src/js/utils/datepicker.js
  cypress/integration/main_page_spec.js
  test/reducers/datepicker.js
  test/utils/datepicker.js
Labels: Work In Progress

#693 Cumulus 1790 Update stats to work with datepicker
  CHANGELOG.md
  app/src/js/actions/index.js
  app/src/js/components/Datepicker/Datepicker.js
  app/src/js/components/Datepicker/Datepicker.scss
  app/src/js/reducers/datepicker.js
  app/src/js/utils/datepicker.js
  cypress/integration/main_page_spec.js
  test/reducers/datepicker.js
  test/utils/datepicker.js
Labels: Needs Review

#649 [CUMULUS-1467] Datepicker changes update Distribution Metrics
  app/src/js/actions/index.js
  app/src/js/components/home.js
  app/src/js/utils/kibana.js
  cypress/fixtures/elasticsearch.json
  cypress/fixtures/updated_elasticsearch.json
  cypress/integration/main_page_spec.js
  localAPI/docker-compose-dashboard.yml
  package-lock.json
  test/components/homepage/home.js
  test/utils/kibana.js
Labels: Needs Review

#703 Cumulus 1796 prevent state mutations in Dashboard reducers
  app/src/js/App.js
  app/src/js/actions/index.js
  app/src/js/components/Edit/edit.js
  app/src/js/components/Executions/execution-status.js
  app/src/js/components/Providers/overview.js
  app/src/js/reducers/api-version.js
  app/src/js/reducers/api.js
  app/src/js/reducers/collections.js
  app/src/js/reducers/cumulus-instance.js
  app/src/js/reducers/datepicker.js
  app/src/js/reducers/dist.js
  app/src/js/reducers/execution-logs.js
  app/src/js/reducers/execution-status.js
  app/src/js/reducers/executions.js
  app/src/js/reducers/granule-csv.js
  app/src/js/reducers/granules.js
  app/src/js/reducers/logs.js
  app/src/js/reducers/mmtLinks.js
  app/src/js/reducers/operations.js
  app/src/js/reducers/pdrs.js
  app/src/js/reducers/providers.js
  app/src/js/reducers/reconciliation-reports.js
  app/src/js/reducers/rules.js
  app/src/js/reducers/schema.js
  app/src/js/reducers/stats.js
  app/src/js/reducers/workflows.js
  app/src/js/store/configureStore.js
  app/src/js/utils/format.js
  cypress/support/commands.js
  package-lock.json
  package.json
  test/reducers/api-version.js
  test/reducers/datepicker.js
  test/reducers/granule-csv.js
  test/reducers/mmtLinks.js
  test/reducers/stats.js
Labels: In Review

#695 Cumulus-1533 Adds confirmation modal for rule enable/disable
  app/src/js/components/AsyncCommands/AsyncCommands.js
  app/src/js/components/DropDown/dropdown-async-command.js
  app/src/js/components/Modal/modal.js
  app/src/js/components/Rules/rule.js
  app/src/js/utils/format.js
  cypress/integration/rules_spec.js
Labels: Work In Progress

#705 Cumulus 1796 fix datepicker state dates
  app/src/js/components/Datepicker/Datepicker.js
  app/src/js/reducers/assign-date.js
  app/src/js/reducers/datepicker.js
  app/src/js/reducers/dist.js
  app/src/js/reducers/logs.js
  app/src/js/reducers/workflows.js
  app/src/js/utils/datepicker.js
  app/src/js/utils/kibana.js
  test/actions/datefilters.js
  test/reducers/dist.js
  test/reducers/stats.js
  test/utils/datepicker.js
  test/utils/kibana.js
Labels: Needs Review
