Repository nasa/cumulus-dashboard, pull requests merged in 2021-04, with the labels that each got.

#948 Upgrade to cypress 7.0.0
  CHANGELOG.md
  cypress/integration/collections_spec.js
  cypress/integration/executions_spec.js
  cypress/integration/logs_spec.js
  localAPI/docker-compose-cypress.yml
  package-lock.json
  package.json
Labels: Needs Review

#952 Misconfigured ES Credentials now show an error on the dashboard.
  CHANGELOG.md
  app/src/js/components/home.js
  app/src/js/middleware/request.js
  package-lock.json
  test/middleware/request.js
Labels: PR Feedback

#949 Cumulus 2430
  CHANGELOG.md
  app/src/css/_chart.scss
  app/src/css/modules/_table.scss
  app/src/js/components/Overview/overview.js
  app/src/js/utils/format.js
Labels: PR Feedback

#947 CUMULUS-2348: Granule Recovery status
  CHANGELOG.md
  README.md
  app/src/css/_base.scss
  app/src/css/_buttons.scss
  app/src/css/modules/_modals.scss
  app/src/js/actions/index.js
  app/src/js/actions/types.js
  app/src/js/components/Granules/bulk-granule-modal.js
  app/src/js/components/Granules/bulk.js
  app/src/js/components/Granules/granule.js
  app/src/js/components/Granules/list.js
  app/src/js/components/Granules/overview.js
  app/src/js/components/Table/Table.js
  app/src/js/reducers/granules.js
  app/src/js/utils/format.js
  app/src/js/utils/table-config/granules.js
  bamboo/set-bamboo-env-variables.sh
  cypress/integration/bulk_granules_spec.js
  cypress/integration/granules_spec.js
  cypress/integration/logs_spec.js
  localAPI/docker-compose-dashboard.yml
  package-lock.json
  package.json
  test/components/granules/bulk.js
Labels: PR Feedback

#951 CUMULUS-2449 Encode collection versions
  CHANGELOG.md
  app/src/js/actions/index.js
  app/src/js/components/Collections/add.js
  app/src/js/components/Collections/collection-header.js
  app/src/js/components/Collections/edit.js
  app/src/js/components/Collections/granules.js
  app/src/js/components/Collections/ingest.js
  app/src/js/components/Collections/logs.js
  app/src/js/components/Collections/overview.js
  app/src/js/utils/format.js
  app/src/js/utils/table-config/collections.js
  app/src/js/utils/table-config/reconciliation-reports.js
  cypress/fixtures/TESTCOLLECTION___Test%2F006.json
  cypress/fixtures/seeds/collectionsFixture.json
  cypress/fixtures/seeds/granulesFixture.json
  cypress/integration/collections_spec.js
  cypress/integration/granules_spec.js
  cypress/integration/main_page_spec.js
  test/utils/format.js
Labels: PR Feedback

#955 Home page refactor + new header.
  CHANGELOG.md
  app/src/css/_base.scss
  app/src/css/_typography.scss
  app/src/js/actions/index.js
  app/src/js/components/Collections/overview.js
  app/src/js/components/Section/section.js
  app/src/js/components/home.js
  test/components/homepage/home.js
Labels: Needs Review, PR Feedback

#957 [CUMULUS-2435] Add step name to execution events
  CHANGELOG.md
  app/src/js/components/Executions/execution-events.js
  app/src/js/utils/table-config/execution-status.js
  cypress/integration/executions_spec.js
  test/components/executions/execution-events.js
Labels: Needs Review
