Repository nasa/cumulus-dashboard, pull requests merged in 2021-06, with the labels that each got.

#967 Whitelist new vulnerability dns-packet
  audit-ci.json
Labels: Needs Review

#964 Update ES and Kibana internals to reflect current metrics state.
  CHANGELOG.md
  README.md
  app/src/js/actions/actions-metrics/apiGatewaySearch.js
  app/src/js/actions/actions-metrics/apiLambdaSearch.js
  app/src/js/actions/actions-metrics/s3AccessSearch.js
  app/src/js/actions/actions-metrics/searchTarget.js
  app/src/js/actions/actions-metrics/teaLambdaSearch.js
  app/src/js/actions/index.js
  app/src/js/components/Header/header.js
  app/src/js/components/home.js
  app/src/js/config/config.js
  app/src/js/utils/kibana.js
  ava-conditional.config.cjs
  bamboo/set-bamboo-env-variables.sh
  cypress/integration/main_page_spec.js
  localAPI/docker-compose-cypress.yml
  localAPI/docker-compose-dashboard.yml
  package-lock.json
  package.json
  test/actions/metrics/condition.js
  test/utils/kibana.js
  webpack.common.js
Labels: In Review

#971 CUMULUS-2544
  CHANGELOG.md
  app/src/js/utils/format.js
  cypress/integration/collections_spec.js
  cypress/integration/executions_spec.js
  cypress/integration/granules_spec.js
  cypress/integration/pdrs_spec.js
Labels: In Review

#976 CUMULUS-2534
  CHANGELOG.md
  app/src/css/_buttons.scss
  app/src/js/components/BatchAsyncCommands/BatchAsyncCommands.js
  app/src/js/components/Errors/copy-to-clipboard.js
  app/src/js/components/Errors/report.js
Labels: Needs Review, PR Feedback
