Repository nasa/cumulus-dashboard, pull requests merged in 2022-03, with the labels that each got.

#1036 CUMULUS-2704:Add option to create ORCA Reconciliation Report to dashboard
  CHANGELOG.md
  app/src/js/components/Form/_form.scss
  app/src/js/components/ReconciliationReports/create.js
  app/src/js/components/ReconciliationReports/orca-backup-report.js
  app/src/js/components/ReconciliationReports/reconciliation-report.js
  app/src/js/utils/table-config/reconciliation-reports.js
  app/src/js/utils/type.js
  cypress/fixtures/seeds/granulesFixture.json
  cypress/fixtures/seeds/reconciliation-reports/InternalReport092020.json
  cypress/fixtures/seeds/reconciliation-reports/orcaBackupReport-20220111T191341153.json
  cypress/fixtures/seeds/reconciliationReportFixture.json
  cypress/integration/granules_spec.js
  cypress/integration/reconciliation_spec.js
  cypress/integration/rules_spec.js
  package-lock.json
  package.json
Labels: In Review, feature/rds-phase-2

#1060 [CUMULUS-2728] Remove Cloud Metrics dependencies from Dashboard
  CHANGELOG.md
  README.md
  app/src/js/actions/actions-metrics/apiGatewaySearch.js
  app/src/js/actions/actions-metrics/apiLambdaSearch.js
  app/src/js/actions/actions-metrics/s3AccessSearch.js
  app/src/js/actions/actions-metrics/searchTarget.js
  app/src/js/actions/actions-metrics/teaLambdaSearch.js
  app/src/js/actions/index.js
  app/src/js/actions/types.js
  app/src/js/components/Header/header.js
  app/src/js/components/home.js
  app/src/js/config/config.js
  app/src/js/reducers/dist.js
  app/src/js/reducers/index.js
  app/src/js/utils/basic-auth.js
  app/src/js/utils/kibana.js
  app/src/js/utils/table-config/execution-status.js
  ava-conditional.config.cjs
  bamboo/set-bamboo-env-variables.sh
  cypress/integration/main_page_spec.js
  docker/Dockerfile
  docker/docker-compose.yml
  localAPI/docker-compose-dashboard.yml
  package.json
  test/actions/metrics/condition.js
  test/actions/metrics/metrics.js
  test/components/homepage/condition.js
  test/components/homepage/home.js
  test/reducers/dist.js
  test/utils/kibana.js
  webpack.common.js
Labels: In Review

#1057 merge feature/rds-phase-2 to develop
  CHANGELOG.md
  app/src/js/components/Form/_form.scss
  app/src/js/components/ReconciliationReports/create.js
  app/src/js/components/ReconciliationReports/orca-backup-report.js
  app/src/js/components/ReconciliationReports/reconciliation-report.js
  app/src/js/utils/table-config/reconciliation-reports.js
  app/src/js/utils/type.js
  cypress/fixtures/seeds/granulesFixture.json
  cypress/fixtures/seeds/reconciliation-reports/InternalReport092020.json
  cypress/fixtures/seeds/reconciliation-reports/orcaBackupReport-20220111T191341153.json
  cypress/fixtures/seeds/reconciliationReportFixture.json
  cypress/integration/granules_spec.js
  cypress/integration/reconciliation_spec.js
  package-lock.json
  package.json
Labels: Needs Review
